name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Set lower case owner name
      - name: Set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >> $GITHUB_ENV
        env:
          OWNER: "${{ github.repository_owner }}"

  services:
    runs-on: ubuntu-latest
    needs: build-and-deploy

    strategy:
      matrix:
        service: [api, sender, thread]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd ${{ matrix.service }} && npm ci || true

      - name: Lint and Test
        run: |
          cd ${{ matrix.service }}
          npm run lint || true
          npm run test || true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.service }} image
        run: |
          docker build -t ghcr.io/${OWNER_LC}/forum-${{ matrix.service }}:${{ github.sha }} ./${{ matrix.service }}
          docker push ghcr.io/${OWNER_LC}/forum-${{ matrix.service }}:${{ github.sha }}

  versioning:
    runs-on: ubuntu-latest
    needs: services

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install root dependencies
        run: npm ci

      - name: Bump version and generate changelog
        run: |
          npx standard-version
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com

      - name: Push version bump and changelog
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git push --follow-tags origin main
